language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install scipy
  - pip install numpy
  - pip install sklearn
  # - pip install python-coveralls
  # - pip install coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install nose

# command to run tests
script:
#  - cd Cluster_Index_lib/ &&
  - cd Cluster_Index_lib/ && python setup.py install
  # - nosetests --with-coverage
  - py.test --cov-config .coveragerc --cov=flashtext tests/ --doctest-modules -v --cov-report term-missing
after_success:
  - coveralls
