language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install scipy numpy sklearn
# command to run tests
script:
  - cd cluster_index_lib && python -m unittest
