language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install scipy
  - pip install numpy
  - pip install sklearn
  - pip install python-coveralls
  - pip install coverage
  - pip install nose

# command to run tests
script:
#  - cd Cluster_Index_lib/ && python -m unittest discover
  - python setup.py install
  - nosetests --with-coverage
after_success:
  - coveralls
