language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install scipy
  - pip install numpy
  - pip install sklearn
  - pip install python-coveralls
  - pip install coverage

# command to run tests
script:
  - cd Cluster_Index_lib/ && python -m unittest discover
after_success:
  - coveralls
